"""initial migration

Revision ID: d2b052a9a07c
Revises: 
Create Date: 2024-09-05 12:42:11.668941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b052a9a07c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signUpType', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=200), nullable=True),
    sa.Column('can_cancel', sa.Boolean(), nullable=False),
    sa.Column('can_comment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('signup_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=200), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('signUpLimit', sa.SmallInteger(), nullable=True),
    sa.Column('signup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['signup_id'], ['signup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup_slot_user',
    sa.Column('signup_slot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['signup_slot_id'], ['signup_slot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('signup_slot_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signup_slot_user')
    op.drop_table('signup_slot')
    op.drop_table('user')
    op.drop_table('signup')
    # ### end Alembic commands ###
